server.port=8080

# Route vers le backend
spring.cloud.gateway.routes[0].id=starwave-backend
spring.cloud.gateway.routes[0].uri=http://localhost:8081
spring.cloud.gateway.routes[0].predicates[0]=Path=/api/**

# OAuth2
spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:9999/auth/realms/starwave