# STARWAVE Backend – Configuration profil STAGING
spring.application.name=starwave-backend
# Java 25 Virtual Threads activé
spring.threads.virtual.enabled=true
server.port=8081
server.servlet.context-path=/api
management.endpoints.web.exposure.include=health,info
management.endpoints.web.base-path=/actuator
management.endpoint.health.show-details=when_authorized
management.server.port=8099
management.server.address=0.0.0.0
logging.level.root=INFO
logging.level.com.ruffinjy.starwave=INFO
